# Generated by Django 3.0 on 2019-12-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='component',
            field=models.ManyToManyField(related_name='component', to='app.Component'),
        ),
    ]
